"""empty message

Revision ID: 784fedaa8de2
Revises: 3d065e3b5002
Create Date: 2020-12-20 20:11:47.197704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '784fedaa8de2'
down_revision = '3d065e3b5002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('edit_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('draft')
    # ### end Alembic commands ###
